language: r
r: bioc-devel
cache: packages
dist: trusty
sudo: required

warnings_are_errors: true

apt_packages:
  - qpdf

r_packages:
  - devtools
  
r_github_packages:
  - cran/callr
  - hadley/pkgdown

script:
  - R CMD build . ${R_BUILD_ARGS}
  - R CMD check `ls -1t *.tar.gz | head -n 1` ${R_CHECK_ARGS}$
  - R CMD INSTALL `ls -1t *.tar.gz | head -n 1`

notifications:
  email: false

after_success:
  - Rscript -e 'pkgdown::build_site()'
  - mv docs ..
  - rm -r *
  - mv ../docs/* .
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN
  on:
    branch: master
  target_branch: gh-pages
  
env:
   global:
     - R_BUILD_ARGS=""
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran --compact-vignettes=gs+qpdf"

cran: http://cran.rstudio.com
